---
name: Test workflow
on:
  push:

jobs:

  all-environment-vars:
    name: Show all environment vars
    runs-on: ubuntu-latest
    steps:
    - run: env | sort
    - run: echo ${{ vars.DS_TEST }}
    