---
name: Test workflow
on:
  push:

jobs:

  all-environment-vars:
    name: Show all environment vars
    runs-on: ubuntu-latest
    steps:
    - run: env | sort
    - run: echo ${{ vars.DS_TEST }}
  print-only-on-main:
    name: Print only on main
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
    - run: echo "ON MAIN!"
    - run: echo ${{ github.ref_name }}
    - run: echo ${{ github.ref_type }}